In [6]:
import numpy as np
from numpy.linalg import inv
a12 = 142.857
a23 = 100.
a34 = 166.667
a41 = 20.

In [2]:
B = np.array([[-242.857, 100., 0], [100., -266.667, 166.667], [0, 166.667, -186.667]])
Pinj = np.array([[1.7],[-1.7],[-4.]])

In [3]:
Binv = inv(B)
print(Binv)
print(Pinj)

[[-0.00632877 -0.00536987 -0.00479453]
 [-0.00536987 -0.0130411  -0.01164384]
 [-0.00479453 -0.01164384 -0.01575342]]
[[ 1.7]
 [-1.7]
 [-4. ]]


In [4]:
T=np.dot(-Binv,Pinj)

In [5]:
print(T)

[[-0.01754796]
 [-0.05961646]
 [-0.07465753]]


In [13]:
T = np.insert(T,0,0)


In [14]:
T

array([ 0.        , -0.01754796, -0.05961646, -0.07465753])

In [22]:
p12=a12*(T[0]-T[1])
p23=a23*(T[1]-T[2])
p34=a34*(T[2]-T[3])
p41=a41*(T[3]-T[0])
print("p12 -->",p12)
print("p23 -->",p23)
print("p34 -->",p34)
print("p41 -->",p41)

p12 --> 2.50684948677
p23 --> 4.20684948677
p34 --> 2.50684948677
p41 --> -1.49315051323
